apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-w8wz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-w8wz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-w8wz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-w8wz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-w8wz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eppr-tenant/rhtap-demo-app/hacbs-test-project-w8wz@sha256:3c2d7970044fe70a04c2be7426eb9b86fca9b24cce5ea2d00b65088c53393a20
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
