apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-w8wz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-eppr-tenant/rhtap-demo-app/hacbs-test-project-w8wz@sha256:3c2d7970044fe70a04c2be7426eb9b86fca9b24cce5ea2d00b65088c53393a20
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
